### ISSUE TITLE
Install aux battery in van

### ISSUE THREAD

**Issue by 3906251** [405447377/denofdomesticity#6]
Remove old crappy batt; put in deep cycle batt.  Make sure not to kill self in progress.

**Comment by 3906251** [comment]
GoF is 2015.09.06 through 2015.09.09; should have the battery installed and tested by at least July

**Comment by 405447377** [comment]
Initial install complete.  Still needed: fit grounded out positive cable with new end, remove electrical tape and reinstall leads to battery

**Comment by 3906251** [comment]
finished
